name: smartwallet
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.2
  bloc: ^8.1.1
  url_launcher: ^6.1.10
  flutter_bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  pin_code_fields: ^7.4.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
#    - assets/icons/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf


